<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM1Kl20x\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM1Kl20x/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerM1Kl20x.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerM1Kl20x\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerM1Kl20x\App_KernelDevDebugContainer([
    'container.build_hash' => 'M1Kl20x',
    'container.build_id' => '39d583b9',
    'container.build_time' => 1619635588,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM1Kl20x');
